#　開発用 docker-compose.yml

version: "3.9"

services:
  frontend:
    build:
      context: .
      target: dev
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true  # ファイル変更検知のための設定（Mac用）
    volumes:
      - .:/app               # ソースコード同期
      - /app/node_modules    # node_modulesはコンテナ内保持
    ports:
      - "5173:5173"
    command: npm run dev
